version: '2'
services:    
  app:
    container_name: web 
    image: web
    build: 
      context: . 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    volumes:
      - './:/app'  
 
